# Generated by Django 4.1.3 on 2022-12-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetingplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location', models.CharField(max_length=30)),
                ('people', models.IntegerField(choices=[(1, 'One'), (2, 'Twotofour'), (3, 'Five')])),
                ('table', models.IntegerField(choices=[(1, 'Circle'), (2, 'Rectangle'), (3, 'Window'), (4, 'Sitting')])),
                ('outlet', models.IntegerField(choices=[(0, 'None'), (1, 'All'), (2, 'Some')])),
                ('meeting_room', models.BooleanField(default=False)),
                ('smoking_room', models.BooleanField(default=False)),
                ('meeting', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'meetingplaces',
            },
        ),
    ]
